version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      args:
        - DOCKER_USER_UID=${DOCKER_USER_UID}
        - DOCKER_USER_GID=${DOCKER_USER_GID}
        - XDEBUG_VERSION=2.7.2
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ../:/var/www
    user: ${DOCKER_USER_UID}:${DOCKER_USER_GID}

  # The Web Server
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443

  # MySQL
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306

volumes:
  mysql:
